version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: on-failure
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5432:5432"
  minio:
    image: minio/minio:RELEASE.2022-10-08T20-11-00Z
    volumes:
      - minio_data:/data
    ports:
      - 9000:9000
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
volumes:
  db_data:
  minio_data:
